# Compiler name (with path, if not in path)
CC=arm-arago-linux-gnueabi-gcc

# Kernel base directory name with path
#KERNEL_DIR=<fill this>

# Mainly used for include paths
CFLAGS=-I $(KERNEL_DIR)

default:
	$(MAKE) saWatchdog

clean:
	rm saWatchdog

